global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: cadvisor
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - cadvisor:8080
    relabel_configs:
    - separator: ;
      regex: (.*)
      target_label: instance
      replacement: cadvisor
      action: replace