version: '3.6'
    
networks:
  admin:
    name: twinficient-admin
    internal: true
  proxy:
    name: twinficient-proxy
    internal: false

services:      
  portainer:
    image: portainer/portainer-ce:2.18.2
    container_name: portainer
    restart: always
    command: --admin-password-file=/secrets/admin-password
    environment:
      VIRTUAL_HOST: portainer.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/portainer/admin-password:/secrets/admin-password
    networks:
      - admin
      - proxy

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.3.1-alpine
    container_name: proxy
    restart: always
    ports:
    - "80:80"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: ${EXTERNAL_HOSTNAME}
    networks:
    - proxy
