version: '3.6'

networks:
  aas:
    name: twinficient-aas
    internal: true

services:    
  aas-registry-dotaas:
    image: dfkibasys/aas-registry-dotaas-part2-log-mem:${AAS_REGISTRY_VERSION}
    container_name: aas-registry-dotaas
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./config/02_aas-registry.yml:/workspace/config/application.yml
    environment:
      VIRTUAL_HOST: aasregistry.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8080
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
       - aas
       - proxy

  aas-server:
    image: dfkibasys/aas-server:${VERSION}
    container_name: aas-server
    ports:
      - 8088:8088
    depends_on:
      - aas-registry-dotaas
    volumes:
      - ./config/02_aas-server.yml:/workspace/config/application.yml
      - ./data/aasx:/workspace/data
    restart: always
    environment:
      EXTERNAL_HOSTNAME: aasserver.${EXTERNAL_HOSTNAME}
      VIRTUAL_HOST: aasserver.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 8088    
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    networks:
       - aas
       - proxy

  ppr-dashboard:
    image: dfkibasys/ppr-dashboard:${PPR_DASHBOARD_VERSION}
    container_name: ppr-dashboard
    environment:
      VITE_AAS_REGISTRY_URL: "http://aasregistry.${EXTERNAL_HOSTNAME}"
      VITE_AJAX_REQUEST_DOMAIN: "http://pprdashboard.${EXTERNAL_HOSTNAME}/engine-rest"
      VUE_APP_AAS_REGISTRY_URL: "http://aasregistry.${EXTERNAL_HOSTNAME}"
      VUE_APP_AJAX_REQUEST_DOMAIN: "http://pprdashboard.${EXTERNAL_HOSTNAME}/engine-rest"
      VIRTUAL_HOST: pprdashboard.${EXTERNAL_HOSTNAME}
      VIRTUAL_PORT: 80

      # these values should be optional -> also remove Processes tab if they are not available
      # -> remove basysafe tab (let basysafe tab be configurable via env variable)
      # invalid number of arguments in "proxy_pass" directive in /etc/nginx/conf.d/default.conf:12
      NGINX_PROXY: "http://aas-server:3000/engine-rest/"
      # required fields
      VUE_APP_CAMUNDA_REST_URL: http://camunda.twinficient.dummy 
      VUE_APP_MQTT_BROKER_URL: http://mqtt.twinficient.dummy
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    restart: always
    networks:
      - aas
      - proxy


