apiVersion: 1
groups:
    - orgId: 1
      name: 30s-evaluation
      folder: alerts
      interval: 30s
      rules:
        - uid: ad39f071-fd39-4ad0-be0d-91a586ac64a1
          title: Disk Space Usage over 70%
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 21600
                to: 0
              datasourceUid: SNpaCLr4z
              model:
                datasource:
                    type: prometheus
                    uid: SNpaCLr4z
                expr: 100 - ((node_filesystem_avail_bytes{instance="node-exporter:9100",job="node",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance="node-exporter:9100",job="node",device!~'rootfs'})
                format: time_series
                interval: ""
                intervalFactor: 1
                intervalMs: 15000
                legendFormat: '{{mountpoint}}'
                maxDataPoints: 43200
                refId: A
                step: 240
            - refId: B
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params: []
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - B
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                reducer: last
                refId: B
                settings:
                    mode: replaceNN
                    replaceWithValue: 0
                type: reduce
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 70
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: ac6c8ec7-7389-47ae-b726-ce308baa135b
          panelId: 4
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            __dashboardUid__: ac6c8ec7-7389-47ae-b726-ce308baa135b
            __panelId__: "4"
            summary: The disk space usage for a partition is over 70%
          isPaused: false
